# Generated by Django 3.2.4 on 2021-06-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='needs to change', max_length=128)),
                ('salary', models.DecimalField(decimal_places=4, default=0.0, help_text='needs to change', max_digits=20)),
                ('salary_net', models.DecimalField(decimal_places=4, default=0.0, help_text='needs to change', max_digits=20)),
                ('day_hours', models.DecimalField(decimal_places=4, default=0.0, help_text='needs to change', max_digits=20)),
                ('vacation_days', models.DecimalField(decimal_places=4, default=0.0, help_text='needs to change', max_digits=20)),
                ('travel_time', models.DecimalField(decimal_places=4, default=0.0, help_text='needs to change', max_digits=20)),
                ('sickdays_value', models.CharField(help_text='needs to change', max_length=128)),
                ('pension', models.DecimalField(decimal_places=4, default=0.0, help_text='needs to change', max_digits=20)),
                ('pitzuim', models.DecimalField(decimal_places=4, default=0.0, help_text='needs to change', max_digits=20)),
                ('hishtalmut', models.DecimalField(decimal_places=4, default=0.0, help_text='needs to change', max_digits=20)),
                ('nesiot_income', models.DecimalField(decimal_places=4, default=0.0, help_text='needs to change', max_digits=20)),
                ('gas_cost', models.DecimalField(decimal_places=4, default=0.0, help_text='needs to change', max_digits=20)),
                ('lunch', models.DecimalField(decimal_places=4, default=0.0, help_text='needs to change', max_digits=20)),
                ('holidays_like_friday', models.CharField(help_text='needs to change', max_length=128)),
                ('chol_hamoed', models.DecimalField(decimal_places=4, default=0.0, help_text='needs to change', max_digits=20)),
                ('minimum_hours_aday', models.DecimalField(decimal_places=4, default=0.0, help_text='needs to change', max_digits=20)),
                ('parking', models.DecimalField(decimal_places=4, default=0.0, help_text='needs to change', max_digits=20)),
                ('flexable_hours', models.CharField(help_text='needs to change', max_length=128)),
            ],
        ),
    ]
